### PR TITLE
Binding for Perl5

### PR DESCRIPTION
**Pull request by klesteb**
I have added bindings for Perl5 using SWIG. I have also added some examples and tried to integrate these changes into the build system. I am not familiar with autoconf, so I probably make some mistakes.

### CODE REVIEW

**Comment by tiian** [comment]
Dear Kevin,
first of all: thank you so much for your work.
I didn't implement a Perl binding because I don't know Perl, but I'm very happy that someone did the job.

As a general feedback, I would like to obtain a polished and smooth integration in the FLoM code base preserving your own intellectual property.

A really important question: are you available for bug fixing and user support if necessary?
In the event that you cannot support the project I will have to document the Perl5 binding as "experimental, unsupported" because I will not be able to support it directly.

I have not yet tried the code but I'm going to test it in the next few days.
As an initial feedback I have checked the changed/added files: it's just an initial feedback that will require future refinements.

Files doc/example/*.pl
The example programs should have a license statement. You can choose any license that's compatible with FLoM's license (GNU GPL 2). Suggested license, for the sake of uniformity, is GNU GPL 2.
An example header can be grabbed from other examples, like Python ones.
The file "advance.pl" should be renamed to "advanced.pl" just for the sake of uniformity.

The logic implemented is similar but not identical to the examples supplied for the other languages: this is acceptable on my side because it's your original contribution, but pay attention that some users could complain.

File src/perl5/Makefile.PL
Hard wired references to "glib" and "libflom" should be replaced by configurable ones (see src/python/setup.py.i for a viable example).
The comment explains that "libgnome2-dev" is a pre-condition: it's necessary to add some tests in configure.ac to test "libgnome2-dev" availability... It will require some hacking starting from these information: https://packages.debian.org/jessie/amd64/libgnome2-dev/filelist

File src/perl5/Makefile.am
It seems to me that there's no "uninstall" operation and some users could complain about it. Take a look to src/python/Makefile.am for an example with a non trivial uninstall phase. Frankly speaking I don't remember the difference between "*-local" and "*-hook" but it could be a second stage refinement.

Files src/perl5/test/*.pl
It seems to me that this directory contains the same examples of "doc/example/*.pl", am I right?

Last but not least, every FLoM artifact is testable, and Perl5 binding cannot be an exception. Autotest file "tests/api.at.in" should be enriched with Perl5 tests or alternatively a new file like "tests/api_perl5.at.in" can be created and it must be referenced by "tests/testsuite.at"

Best Regards
Ch.F.

**Comment by klesteb** [comment]
Thanks for the feedback. I already made the changes requested for the examples. And yes, the code in src/perl5/test is a copy of what is in examples and probably doesn't need to be distributed. It was just me, getting a feeling for the call interface. I also have no problems supporting the Perl code.

There is no 'uninstall' option with the Perl build process. There is also no way of getting a listing of files installed like what setup.py is doing.  This is a "feature" of the build system. My fix for this feature is to use the native package manager for file manipulation. 

I guess, my challenge is to make the Perl way coexist in an autoconf world. Similar concepts, different implementations.

**Comment by klesteb** [comment]
Apparently I pushed the wrong button.

**Comment by tiian** [comment]
I have started to merge your work creating a dedicated branch named "perl5_merge".
The first issue that I have met is related to configure.ac check for Perl5 "perl-config" utility program: I've googled around a little bit to understand the necessary package in Ubuntu Linux, but no reference to "perl-config" utility program. Do you have any hint?

**Comment by klesteb** [comment]
I haven't clue if such a package exists. I added it to mimic the python section. 

I think that I may have addressed most of your concerns with the latest update. My question is how strict is autotest usage for automated testing?   autotest seems to be geared towards compiling small chunks of code, running that code, and checking exit status and output against a know result. 

Perl itself, has a extensive testing facility. A "make check" will now run the Perl based tests. If the tests complete successfully an exit status of 0 is returned.  Is this "good enough"? They primarily test the interface, not functionality. It appears there is already quite a few functionality tests.

**Comment by klesteb** [comment]
Perl and SWIG are the only tools needed to build the package.

**Comment by tiian** [comment]
I have just polished the build procedure in branch "perl5_merge":

- Perl build scripts do not use Python variables anymore
- removed intermediate build files from git repo
- fixed autoconf stuff
- fixed the artifact (tarball) produced by make dist: the tarball now can be configured and compiled

I have executed without any issue the Perl5 examples.
Next planned step: automatic testing implementation.

In the meantime, I suggest you to align your local repo to my last commit (028aa37b03bb134a44492ed81f1060bd9849ace1).

**Comment by tiian** [comment]
I have started to set up the autotest scaffolding, but in the meantime I have discovered a "chicken and egg issue" related to the Perl5 module.
If a user configure FLoM in a system without a prior installation, "libflom" library is not installed in /usr/local/lib.
In this way, the Perl5 module build ends with an error related to **libflom**:

Running Mkbootstrap for Flom ()
chmod 644 Flom.bs
rm -f blib/arch/auto/Flom/Flom.so
LD_RUN_PATH="/usr/local/lib" cc  -shared -O2 -g -L/usr/local/lib -fstack-protector flom_wrap.o  -o blib/arch/auto/Flom/Flom.so 	\
	   -lglib-2.0 -lgthread-2.0 -ldbus-1 -lssl -lcrypto -**lflom**  	\
	  
/usr/bin/ld: cannot find -lflom
collect2: ld returned 1 exit status

the linker is not able to find "flom" library because it's not yet installed.
This issue can be fixed pointing the built but not installed library adding a linker directive to Makefile.PL.in like below:

$libs = ' -l@GLIB2_PERL@';
$libs .= ' -l@GTHREAD2_PERL@';
$libs .= ' -l@DBUS1_PERL@';
$libs .= ' -l@OPENSSL_PERL@';
$libs .= ' -l@CRYPTO_PERL@';
**$libs .= ' -L@abs_top_builddir@/src/.libs';**
$libs .= ' -l@_FLOM_PREFIX@';

This action unfortunately does not solve the issue, because now the module is referring to "libflom" in the build directory even after installation:

$ **ldd /usr/local/lib/perl/5.10.1/auto/Flom/Flom.so**
	linux-vdso.so.1 =>  (0x00007fffbbbff000)
	libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0x00007f38527b4000)
	libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0 (0x00007f38525af000)
	libdbus-1.so.3 => /lib/libdbus-1.so.3 (0x00007f385236f000)
	libssl.so.0.9.8 => /lib/libssl.so.0.9.8 (0x00007f385211b000)
	libcrypto.so.0.9.8 => /lib/libcrypto.so.0.9.8 (0x00007f3851d8a000)
	**libflom.so.0 => /home/tiian/flom_perl5/src/.libs/libflom.so.0 (0x00007f3851b4c000)**
	libc.so.6 => /lib/libc.so.6 (0x00007f38517c3000)
	libpcre.so.3 => /lib/libpcre.so.3 (0x00007f3851595000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f3851377000)
	librt.so.1 => /lib/librt.so.1 (0x00007f385116f000)
	libdl.so.2 => /lib/libdl.so.2 (0x00007f3850f6b000)
	libz.so.1 => /lib/libz.so.1 (0x00007f3850d53000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3852cb3000)

At this point, the module can be loaded but it points a library that's not installed in the system path, but just built in the source tree. 
This type of issue does not happen when library installation is performed by **libtool**, but the Perl module is installed by a makefile produced by Perl utilities.

At this time I can see only 2 "solutions":

1. the user has to build and install FLoM without Perl using "./configure --disable-perl" and, after the installation of "libflom" he has to build again with Perl and install again... It works but sounds bad.
2. there's some way to instrument the Perl module install procedure and **libtool** is used to adjust the linked libraries.

Do you have any hint?

**Comment by klesteb** [comment]
There is option 3, let Perl do it's thing. If the standard procedure is the following:

./configure
make
make check
make install

and everything works, and the tests pass, then is forcing the Perl module into an autotest world, worth the hassle?

**Comment by tiian** [comment]
Commit 92bd14654f6f6012374845fcd3d02cf0fd96a6c5 remove the "chicken and egg" issue if the "flom" library is not already installed at build time (normal condition for a new system).
The Perl module can't be tested before "make install", but at least the behaviour is now aligned with Python module.

**Comment by tiian** [comment]
Today I have merged your Perl5 contribution in the main git tree: Perl API is now a part of FLoM.
Thank you for your contribution.

Best Regards
Ch.F.

**Pull request merged**
